name: kaleyra_video_flutter_plugin
description: Flutter plugin enabling video communication through Kaleyra Video SDKs
version: 2.1.2
homepage: https://www.kaleyra.com/video/
repository: https://github.com/KaleyraVideo/VideoFlutterPlugin
issue_tracker: https://github.com/KaleyraVideo/VideoFlutterPlugin/issues

topics:
  - webrtc
  - voip
  - video
  - chat
  - call

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^4.1.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.20.2
  mockito: ^5.3.2
  build_runner: ^2.2.1

flutter:
  plugin:
    platforms:
      android:
        package: com.kaleyra.video_flutter_plugin
        pluginClass: VideoNativePlugin
      ios:
        pluginClass: VideoNativePlugin

false_secrets:
 - /example/lib/firebase_options.dart
 - /example/android/app/google-services.json