name: Publish Plugin Update to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: macos-latest
    permissions:
      id-token: write # Required for authentication using OIDC
    environment:
      name: release_environment
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - uses: MobileDevOps/flutter-sdk-action@v1.0.0
        with: 
           flutter-sdk-version: 3.27.4

      - name: Install dependencies
        run: flutter pub get

      - name: Publish
        run: dart pub publish --force
