name: Create New Plugin Release

on:
  workflow_dispatch:
    inputs:
      release_kind:
        type: choice
        description: What kind of release do you want to do?
        required: true
        options: 
        - 
        - patch
        - minor
        - major
      changelog:
        type: string
        description: Write a changelog for this release
        required: true

jobs:
  release-plugin:
    runs-on: macos-latest
    environment:
      name: release_environment

    steps:
    - uses: actions/checkout@v2

    - name: Setting up environment 
      run: |
        pip install pyyaml
    - name: Update package version
      run: |
        set -o pipefail
        new_version=$(python update_plugin_version.py ${{ github.event.inputs.release_kind }})
        echo -e "## $new_version\n\n${{ github.event.inputs.changelog }}\n\n$(cat CHANGELOG.md)" > CHANGELOG.md
        git add .
        git commit -m "Updated to version $new_version" 
        git push
