name: Release Plugin

on:
  workflow_dispatch:
    inputs:
      release_kind:
        type: choice
        description: What kind of release do you want to do?
        required: true
        options: 
        - 
        - patch
        - minor
        - major

jobs:
  release-plugin:
    runs-on: macos-latest
    environment:
      name: release_environment

    steps:
    - uses: actions/checkout@v2
    # - uses: MobileDevOps/flutter-sdk-action@v1.0.0

    - name: Setting up environment 
      run: |
        pip install pyyaml
    - name: Update package version
      run: |
        set -o pipefail
        new_version=$(python update_plugin_version.py ${{ github.event.inputs.release_kind }})
        git add .
        git commit -m "Updated to version $new_version" 
        git tag v$new_version
        git push
        git push origin v$new_version