name: Create New Plugin Release

on:
  workflow_call:
   inputs:
      release_kind:
        type: string
        description: What kind of release do you want to do?
        required: false
          
  workflow_dispatch:
    inputs:
      release_kind:
        type: choice
        description: What kind of release do you want to do?
        required: true
        options:
          -
          - patch
          - minor
          - major

jobs:
  release-plugin:
    runs-on: macos-latest
    environment:
      name: create_release
    defaults:
      run:
        working-directory: ./videoFlutterPlugin
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: VideoFlutterPlugin
      - uses: actions/checkout@v2
        with:
          repository: KaleyraVideo/VideoFlutterPlugin
          path: videoFlutterPlugin
          ref: 'main'
          fetch-depth: 0
          fetch-tags: true
          token: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
      - name: Setting up environment
        run: |
          pip install pyyaml
      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install git-subrepo
      - name: Update subrepo
        run: git subrepo pull ios/native-bridge
      - name: Update package version
        id: output_tag
        run: |
          set -o pipefail
          new_version=$(python update_plugin_version.py ${{ inputs.release_kind }})
          echo "TAG=v$new_version" >> $GITHUB_OUTPUT
          last_commit_hash=$(git log -1 --format="%H")
          last_tag_commit_hash=$(git log -1 --format=format:"%H" $(git describe --tags --abbrev=0))
          changelog=$(git log $last_commit_hash...$last_tag_commit_hash --pretty=format:"- %s")
          new_version_changelog="## $new_version\n\n$changelog"
          echo $new_version_changelog
          echo -e "$new_version_changelog\n\n$(cat CHANGELOG.md)" > CHANGELOG.md
      - name: Install dependencies
        uses: MobileDevOps/flutter-sdk-action@v1.0.0
      - run: |
          cd example
          flutter pub get
          cd ios
          pod update KaleyraVideoSDK
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./videoFlutterPlugin
          commit_message: "chore: updated to version ${{ steps.output_tag.outputs.TAG }}"
          tagging_message: "${{ steps.output_tag.outputs.TAG }}"
